### ISSUE TITLE
deleting a story is not working

### ISSUE THREAD

**Issue by huth1** [r0bn/swp2#108]

**Comment by Teammm** [comment]
Can you describe the problem? Because i deleted for like 30 Minutes several test stories and it worked .

**Comment by huth1** [comment]
Occurs when you want to delete a story that is assigned to someone.

**Comment by 9SphynX9** [comment]
If it is assigned to someone, it shouldnt possible for you that you can delete the story. Also it shouldnt possible that you can save this story.

Or is the bug that you cant delete the story which is assigned to yourself?

**Comment by thisisdanny** [comment]
I want to add one thing here:
The described behaviour from 9SphynX9 is correct, the route to delete a story that has a user is protected. This also applies for deleting media files. If a bad request is made, the http response statuscode is 400 (bad request), if the wrong user is given the statuscode is 401 (unauthorized).

**Comment by huth1** [comment]
The story is assigned to me and i want to delet it with my account.

**Comment by r0bn** [comment]
the reason for this bug is obvious simple, some funny person thought that he simply programm is own server api request function instead of politly asking for example the responsible guy. Because with the delete request there have to be send an authentication header !!!!!!!!!!
