### ISSUE TITLE
Change "size" und "radius" attributs into the xml

### ISSUE THREAD

**Issue by Teammm** [r0bn/swp2#17]
"Size" and "Radius" should be a float. Also they should have an extra attribut "uom" (units of measurements) that contains the type.
Size should have: "KB" ; "MB" ; "GB"
Radius should have: meters = "m" ; kilometers = "km" ; world = "w"

**Comment by 9SphynX9** [comment]
Radius uom value should be: meters = "m" ; kilometers = "km"
The tag "world" will not be implemented.

**Comment by 9SphynX9** [comment]
Changed with schema revision 5
