### ISSUE TITLE
GUI Works

### ISSUE THREAD

**Issue by Teammm** [r0bn/swp2#41]
Done:
----------------------------------------------------------

rename tags by given convention: (Arno, Yasin; primary: Arno)
textarea: tta
Label: lbl
Input: in
Button: btn
Dropdown: ddn
form-horizontal: fhl
form-group: fgp
Button-group: bgp
fieldset: fst
checkbox: chb
radioButton: rdb
legend: lgd
column: col
row: row
div: div

Rename Waychooser to Chooser (Arno) in jade
Rename Feature to Storypoint (Arno) in jade

Controlpanel should be in line with all other controlpanels (Arno)

Quiz: labelfix: (lg) (Arno)

Quiz: Answer: Delete "Antwort" in labels : ID | Text (Arno)

Redesign Chooser - Answer: (Arno)
ID - ItemRef - deleteButton
Text - FeatureRef - nothing (1 col)

Feature | Featurename. decrease size of inputfield featureName (Arno)

Chooser label QuizID (Arno)

Change Max-hight of description-Textarea 700 (Arno)

Every Controlpanel: Reorder-Function has to be implemented (Yasin)

Map: (Yasin)
- Radius
- Searchbox -> Autocompletion
- Googlelogin delete
- search button delete
- raise size of map and mapborder (5-10 px) 

MBib has to be implemented for both (Yasin)

Every First-Lvl Feature-Ref of: Item, Chooser and Quiz has to be the assigned FeatureName! (Yasin)

autoscroll of the right side. (Arno)

Feature-Map-button has to be implemented (Yasin)
gpsField: inAnchor... , inLatLngLocation (Yasin)

**Comment by Teammm** [comment]
added to conventions: 
textarea: tta

**Comment by 9SphynX9** [comment]
Ref from mediaLib is now a new ticket for sprint 5...
