### ISSUE TITLE
ToDo Dependency

### ISSUE THREAD

**Issue by 9SphynX9** [r0bn/swp2#42]
TODO
--------------------------------------------------

DONE 
---------------------------------------------------------------
Delete Edges when Delete an Interaction (Yasin)
Trace path of storypointreferences and delete them when button is deleted. (Yasin)
ItemRef in graph (Arno, Yasin)
 -> Show items in the graph on the edge (Yasin) 

All References has to be implemented and has to be dropdown-menues
- dropdown-menues (Arno)

Create Dependency (Arno)
- show Dependency graph into the divDependencyBox for every input (Yasin, Arno)
- Create Dependency function (Yasin)
- show Dependency graph into the divDependencyBox (Yasin, Arno)
- Buttons for OnTrue, On False -- Every buttonclick should refresh the dependencyBox
- Buttons (over Interaktion erstellen)

Dropdown Menues for Chooser (Arno)

**Comment by Teammm** [comment]
Updated
