### ISSUE TITLE
fix href for media files in example xml

### ISSUE THREAD

**Issue by thisisdanny** [r0bn/swp2#44]
only include filenames in xml files

**Comment by Teammm** [comment]
deleted the url from xref:href at the assets in the xml. But also you can create a secound xml file for testing etc. in which you can do those things

**Comment by thisisdanny** [comment]
invalid filename

**Comment by huth1** [comment]
why they are invalid?

**Comment by thisisdanny** [comment]
because we don't allow the file extension: null

check the api documentation for allowed file extensions.

**Comment by huth1** [comment]
can this ticket be closed?

**Comment by thisisdanny** [comment]
yes, we added xml files in /server/docs/xml files that fix this issue.
