### ISSUE TITLE
map no sync correctly

### ISSUE THREAD

**Issue by huth1** [r0bn/swp2#53]
If you change radius and an map, the new radius size is not shown. It is only shown when you move the point.
If you change coordinates of point (in input field), the point isn't moved, when you open the map.

**Comment by 9SphynX9** [comment]
fixed map loading routine for circles.
added default measurement value (Kilometer).

If the user didn't choose a measurement, but tries to set a radius via map, the measurement will be setted to Kilometer and the user gets an alert box with the information.

**Comment by huth1** [comment]
radius is not correct set, when "Einheit" is choosen as measurement
you can delete "Einheit" from the dropbox and choose "meter" as default

**Comment by 9SphynX9** [comment]
changed... default value of measurement is now Meter
