### ISSUE TITLE
references not updated

### ISSUE THREAD

**Issue by huth1** [r0bn/swp2#55]
You choose a story point for a quiz reference. Now you delete this story point. The reference isn't updated in the quiz.
If you change the name of the story point, the same bug occurs.

**Comment by 9SphynX9** [comment]
Dependency problem ->Assigned to Teammm

**Comment by Teammm** [comment]
If you delete a storypoint the reference will be updated in the dropdown field. 
In the case that u change the name of a storypoint we decided after 8 hours of work, that the costs to implement this is too high...
