### ISSUE TITLE
Critical Bug: Authorentool GUI

### ISSUE THREAD

**Issue by 9SphynX9** [r0bn/swp2#64]
Critical Bug: Missing Information about the Story in the GUI. Without this information a story can't be generated.
A Story can't be played as well without this basic informations. The meta data of a Storypoint would be useless, if this, system critical information about the story is missing. Without the information of this extrem important field, the hole project would be useless.
The missing information about the Story meta data is: missing EndOfStory Checkbox.

**Comment by Teammm** [comment]
It took a long time to find the right place and fix this critical bug...  I nearly though i wouldn't make it at all. I almost gave up BUT finally made it!! A Story now can be parsed with all informations needed. The Checkbox now is implemented AND the layout is still good.
