### ISSUE TITLE
GPS search in map is not working

### ISSUE THREAD

**Issue by huth1** [r0bn/swp2#81]
You want to choose a story point and open the map. Now you want to search a city. You write "Stuttgart" in the text field and press enter. There is no city found.

**Comment by 9SphynX9** [comment]
Its again the contingent of google maps... if we load the map more than 2500 times a day, we got banned. This happens every week... The solution is to load a new script from google maps. I will search for a permanent solution of this problem.

**Comment by 9SphynX9** [comment]
fixed... see latest commit in branch authorentool
