### ISSUE TITLE
upload not working

### ISSUE THREAD

**Issue by huth1** [r0bn/swp2#84]
I want to upload a mp4 file with 11,8 MB filesize. The file isn't uploaded and a 405 error return.

POST http://api.storytellar.de/story/140/media 405 (Method Not Allowed)(anonymous function) @ vendor.js:18897sendReq @ vendor.js:18698$get.serverRequest @ vendor.js:18414processQueue @ vendor.js:22279(anonymous function) @ vendor.js:22295$get.Scope.$eval @ vendor.js:23497$get.Scope.$digest @ vendor.js:23313$get.Scope.$apply @ vendor.js:23602(anonymous function) @ vendor.js:30602eventHandler @ vendor.js:12063

**Comment by thisisdanny** [comment]
Tested with: Sequenz_A_1.mp4 (example story in google drive, this is also the story that thomas mentioned here)

Could not replicate with front-end storytellar.de or rest-client, works fine so far.

**Comment by r0bn** [comment]
as well not able to reproduce the problem!
